name: Fetch Sponsorships and commit
description:
  This action fetches the sponsorships of a user or organization and commits the
  data to the repository.
author: Santosh Yadav

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: blue

# Define your inputs here.
inputs:
  GH_USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false
  allow-add-to-readme:
    description: 'Add sponsorship data to README.md'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
